spring:
  profiles: peer1
  application:
    name: com-github-since1986-learn-cloud-service-a

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/,http://eureka3:8003/eureka/
---
spring:
  profiles: peer2
  application:
    name: com-github-since1986-learn-cloud-service-a

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/,http://eureka3:8003/eureka/
---
spring:
  profiles: peer3
  application:
    name: com-github-since1986-learn-cloud-service-a

server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/,http://eureka3:8003/eureka/